//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c3i_fedex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent_case_attempts_made
    {
        public string case_id { get; set; }
        public string agent_id { get; set; }
        public string attempts_made { get; set; }
        public long id { get; set; }
        public Nullable<System.DateTime> attempts_Date { get; set; }
        public Nullable<bool> case_priority { get; set; }
    
        public virtual case_details case_details { get; set; }
    }
}
