//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c3i_fedex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bot_password
    {
        public long id { get; set; }
        public string angetid { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public int flag { get; set; }
    }
}
