//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c3i_fedex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_details
    {
        public case_details()
        {
            this.add_case_notes = new HashSet<add_case_notes>();
            this.agent_case_attempts_made = new HashSet<agent_case_attempts_made>();
            this.agent_case_details = new HashSet<agent_case_details>();
            this.case_notes1 = new HashSet<case_notes>();
            this.folder_ids = new HashSet<folder_ids>();
            this.package_details = new HashSet<package_details>();
            this.package_scan_details = new HashSet<package_scan_details>();
            this.primary_case_details = new HashSet<primary_case_details>();
            this.primary_requirements = new HashSet<primary_requirements>();
            this.recipient_details = new HashSet<recipient_details>();
            this.shipper_details = new HashSet<shipper_details>();
            this.location_details_origion = new HashSet<location_details_origion>();
            this.location_details_origion1 = new HashSet<location_details_origion>();
            this.location_details_dest = new HashSet<location_details_dest>();
        }
    
        public string case_id { get; set; }
        public string alternate_title { get; set; }
        public string title { get; set; }
        public string case_notes { get; set; }
        public string tracking_number { get; set; }
        public Nullable<System.DateTime> commitment_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public Nullable<int> attempts_made { get; set; }
        public Nullable<System.DateTime> follow_up_date { get; set; }
        public Nullable<System.DateTime> assignment { get; set; }
        public Nullable<bool> case_priority { get; set; }
        public string shipper_local_time { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<int> attemsfoldername { get; set; }
    
        public virtual ICollection<add_case_notes> add_case_notes { get; set; }
        public virtual ICollection<agent_case_attempts_made> agent_case_attempts_made { get; set; }
        public virtual ICollection<agent_case_details> agent_case_details { get; set; }
        public virtual ICollection<case_notes> case_notes1 { get; set; }
        public virtual ICollection<folder_ids> folder_ids { get; set; }
        public virtual ICollection<package_details> package_details { get; set; }
        public virtual ICollection<package_scan_details> package_scan_details { get; set; }
        public virtual ICollection<primary_case_details> primary_case_details { get; set; }
        public virtual ICollection<primary_requirements> primary_requirements { get; set; }
        public virtual ICollection<recipient_details> recipient_details { get; set; }
        public virtual ICollection<shipper_details> shipper_details { get; set; }
        public virtual ICollection<location_details_origion> location_details_origion { get; set; }
        public virtual ICollection<location_details_origion> location_details_origion1 { get; set; }
        public virtual ICollection<location_details_dest> location_details_dest { get; set; }
    }
}
