//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c3i_fedex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    //public partial class Incedo_DEVEntities : DbContext
    //{
    //    public Incedo_DEVEntities()
    //        : base("name=Incedo_DEVEntities")
    //    {
    //    }
    
    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }
    
    //    public DbSet<add_case_notes> add_case_notes { get; set; }
    //    public DbSet<agent_case_attempts_made> agent_case_attempts_made { get; set; }
    //    public DbSet<agent_case_details> agent_case_details { get; set; }
    //    public DbSet<agent_details> agent_details { get; set; }
    //    public DbSet<bot_trigger> bot_trigger { get; set; }
    //    public DbSet<case_details> case_details { get; set; }
    //    public DbSet<case_notes> case_notes { get; set; }
    //    public DbSet<folder_details> folder_details { get; set; }
    //    public DbSet<folder_ids> folder_ids { get; set; }
    //    public DbSet<location_details_dest> location_details_dest { get; set; }
    //    public DbSet<location_details_origion> location_details_origion { get; set; }
    //    public DbSet<login> logins { get; set; }
    //    public DbSet<package_details> package_details { get; set; }
    //    public DbSet<primary_case_details> primary_case_details { get; set; }
    //    public DbSet<primary_rep_details> primary_rep_details { get; set; }
    //    public DbSet<primary_requirements> primary_requirements { get; set; }
    //    public DbSet<recipient_details> recipient_details { get; set; }
    //    public DbSet<shipper_details> shipper_details { get; set; }
    //    public DbSet<package_scan_details> package_scan_details { get; set; }
    //}
}
