//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c3i_fedex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class primary_case_details
    {
        public string primary_rep_id { get; set; }
        public string case_id { get; set; }
        public long id { get; set; }
    
        public virtual case_details case_details { get; set; }
    }
}
