//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c3i_fedex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class primary_rep_details
    {
        public string name { get; set; }
        public string fedex_id { get; set; }
        public Nullable<System.DateTime> date_assigned { get; set; }
        public string queue_type { get; set; }
        public string loc_id { get; set; }
        public string email_id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string status { get; set; }
        public long primary_rep_id { get; set; }
    }
}
