//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c3i_fedex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_zone_codes
    {
        public string timezone { get; set; }
        public string standard_time { get; set; }
        public string daylight_time { get; set; }
        public string fedex_codes { get; set; }
        public long id { get; set; }
    }
}
